name: omt_base_project
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.0

  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.0
  flutter_secure_storage: ^8.0.0
  easy_localization: ^3.0.2

  #bloc
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2

  #injector
  get_it: ^7.6.0
  injectable: ^2.3.0

  #network
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  retrofit: ^4.0.1
  pretty_dio_logger: ^1.3.1

  #image
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7

  #annotation
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  auto_route: 7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  freezed: 2.4.1
  auto_route_generator: 7.1.1
  injectable_generator: ^2.4.0
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - .env.dev

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
